version: "3.9"

services:
  app:
    build: .
    container_name: nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - .env:/app/.env
    command: npm run dev