// Opciones para los campos de filiación

export const religionOptions = [
  { value: "CATOLICA", label: "Católica" },
  { value: "EVANGELICA", label: "Evangélica" },
  { value: "TESTIGO_JEHOVA", label: "Testigo de Jehová" },
  { value: "MORMONA", label: "Mormona" },
  { value: "ADVENTISTA", label: "Adventista" },
  { value: "MUSULMANA", label: "Musulmana" },
  { value: "JUDIA", label: "Judía" },
  { value: "BUDISTA", label: "Budista" },
  { value: "HINDUISTA", label: "Hinduista" },
  { value: "AGNOSTICO", label: "Agnóstico" },
  { value: "ATEO", label: "Ateo" },
  { value: "OTRA", label: "Otra" },
  { value: "NO_ESPECIFICA", label: "No especifica" },
];

export const etniaOptions = [
  { value: "MESTIZO", label: "Mestizo" },
  { value: "QUECHUA", label: "Quechua" },
  { value: "AYMARA", label: "Aymara" },
  { value: "AMAZONICO", label: "Amazónico" },
  { value: "BLANCO", label: "Blanco" },
  { value: "NEGRO", label: "Negro/Afroperuano" },
  { value: "ASIATICO", label: "Asiático" },
  { value: "OTRO", label: "Otro" },
  { value: "NO_ESPECIFICA", label: "No especifica" },
];

export const centroPobladoOptions = [
  { value: "URBANO", label: "Urbano" },
  { value: "RURAL", label: "Rural" },
  { value: "URBANO_MARGINAL", label: "Urbano Marginal" },
  { value: "CASERIO", label: "Caserío" },
  { value: "COMUNIDAD", label: "Comunidad" },
  { value: "ANEXO", label: "Anexo" },
  { value: "OTRO", label: "Otro" },
];

export const paisOptions = [
  { value: "PERU", label: "Perú" },
  { value: "ARGENTINA", label: "Argentina" },
  { value: "BOLIVIA", label: "Bolivia" },
  { value: "BRASIL", label: "Brasil" },
  { value: "CHILE", label: "Chile" },
  { value: "COLOMBIA", label: "Colombia" },
  { value: "ECUADOR", label: "Ecuador" },
  { value: "PARAGUAY", label: "Paraguay" },
  { value: "URUGUAY", label: "Uruguay" },
  { value: "VENEZUELA", label: "Venezuela" },
  { value: "MEXICO", label: "México" },
  { value: "ESPAÑA", label: "España" },
  { value: "ESTADOS_UNIDOS", label: "Estados Unidos" },
  { value: "OTRO", label: "Otro" },
];

export const departamentoOptions = [
  { value: "AMAZONAS", label: "Amazonas" },
  { value: "ANCASH", label: "Áncash" },
  { value: "APURIMAC", label: "Apurímac" },
  { value: "AREQUIPA", label: "Arequipa" },
  { value: "AYACUCHO", label: "Ayacucho" },
  { value: "CAJAMARCA", label: "Cajamarca" },
  { value: "CALLAO", label: "Callao" },
  { value: "CUSCO", label: "Cusco" },
  { value: "HUANCAVELICA", label: "Huancavelica" },
  { value: "HUANUCO", label: "Huánuco" },
  { value: "ICA", label: "Ica" },
  { value: "JUNIN", label: "Junín" },
  { value: "LA_LIBERTAD", label: "La Libertad" },
  { value: "LAMBAYEQUE", label: "Lambayeque" },
  { value: "LIMA", label: "Lima" },
  { value: "LORETO", label: "Loreto" },
  { value: "MADRE_DE_DIOS", label: "Madre de Dios" },
  { value: "MOQUEGUA", label: "Moquegua" },
  { value: "PASCO", label: "Pasco" },
  { value: "PIURA", label: "Piura" },
  { value: "PUNO", label: "Puno" },
  { value: "SAN_MARTIN", label: "San Martín" },
  { value: "TACNA", label: "Tacna" },
  { value: "TUMBES", label: "Tumbes" },
  { value: "UCAYALI", label: "Ucayali" },
];

// Distritos de Lima (ejemplo - puedes expandir según necesites)
export const distritoLimaOptions = [
  { value: "LIMA", label: "Lima" },
  { value: "ANCON", label: "Ancón" },
  { value: "ATE", label: "Ate" },
  { value: "BARRANCO", label: "Barranco" },
  { value: "BREÑA", label: "Breña" },
  { value: "CARABAYLLO", label: "Carabayllo" },
  { value: "CHACLACAYO", label: "Chaclacayo" },
  { value: "CHORRILLOS", label: "Chorrillos" },
  { value: "CIENEGUILLA", label: "Cieneguilla" },
  { value: "COMAS", label: "Comas" },
  { value: "EL_AGUSTINO", label: "El Agustino" },
  { value: "INDEPENDENCIA", label: "Independencia" },
  { value: "JESUS_MARIA", label: "Jesús María" },
  { value: "LA_MOLINA", label: "La Molina" },
  { value: "LA_VICTORIA", label: "La Victoria" },
  { value: "LINCE", label: "Lince" },
  { value: "LOS_OLIVOS", label: "Los Olivos" },
  { value: "LURIGANCHO", label: "Lurigancho" },
  { value: "LURIN", label: "Lurín" },
  { value: "MAGDALENA", label: "Magdalena del Mar" },
  { value: "MIRAFLORES", label: "Miraflores" },
  { value: "PACHACAMAC", label: "Pachacámac" },
  { value: "PUCUSANA", label: "Pucusana" },
  { value: "PUEBLO_LIBRE", label: "Pueblo Libre" },
  { value: "PUENTE_PIEDRA", label: "Puente Piedra" },
  { value: "PUNTA_HERMOSA", label: "Punta Hermosa" },
  { value: "PUNTA_NEGRA", label: "Punta Negra" },
  { value: "RIMAC", label: "Rímac" },
  { value: "SAN_BARTOLO", label: "San Bartolo" },
  { value: "SAN_BORJA", label: "San Borja" },
  { value: "SAN_ISIDRO", label: "San Isidro" },
  { value: "SAN_JUAN_DE_LURIGANCHO", label: "San Juan de Lurigancho" },
  { value: "SAN_JUAN_DE_MIRAFLORES", label: "San Juan de Miraflores" },
  { value: "SAN_LUIS", label: "San Luis" },
  { value: "SAN_MARTIN_DE_PORRES", label: "San Martín de Porres" },
  { value: "SAN_MIGUEL", label: "San Miguel" },
  { value: "SANTA_ANITA", label: "Santa Anita" },
  { value: "SANTA_MARIA_DEL_MAR", label: "Santa María del Mar" },
  { value: "SANTA_ROSA", label: "Santa Rosa" },
  { value: "SANTIAGO_DE_SURCO", label: "Santiago de Surco" },
  { value: "SURQUILLO", label: "Surquillo" },
  { value: "VILLA_EL_SALVADOR", label: "Villa El Salvador" },
  { value: "VILLA_MARIA_DEL_TRIUNFO", label: "Villa María del Triunfo" },
];
